spring:
  mail:
    password:
    username:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    port: 587
    host: smtp.gmail.com